#include <array>
#include <vector>
#include <fstream>

// length-6 / length-8 coefficient tables generated by the Julia HPE classifier
#include "w6_table.cpp"            // W6traj / W6D                       (Wilson,   length 6)
#include "poly_68_tables.cpp"      // P6Nt4traj/D, P8Nt4traj_w1/D_w1,
                                   //              P8Nt4traj_w2/D_w2     (Polyakov, length 6/8)
#include "p10_nt4_table.cpp"       // P10Nt4traj   / P10Nt4D             (Polyakov, length 10, winding 1)
#include "p10_nt4_w2_table.cpp"    // P10Nt4traj_w2/ P10Nt4D_w2          (Polyakov, length 10, winding 2)
// W8traj/W8D (length 8) come from HPE/nnlo_safe.cpp -> nnlo_traj_list.cpp
// W10traj/W10D(length 10) come from HPE/nnlo_safe.cpp -> n3lo_traj_list.cpp
// MakeTrajList / MakeTrajListP / cyclic_symmetry also come from HPE/nnlo_safe.cpp

// ===========================================================================
//  hpe_meas.cpp : length-generic HPE measurement (lengths 6 / 8 / 10).
//
//  Wilson type   : symmetry orbit = MakeTrajList  (24 perm x 16 sign),  -2/V
//  Polyakov type : symmetry orbit = MakeTrajListP (6 perm x 8 sign,     +2/V
//                  time fixed), classified by temporal winding number.
//                  Coefficients carry the antiperiodic-BC sign (-1)^(w-1).
//
//  Each path is split at its midpoint into a prefix/suffix trie; the loop
//  trace is Tr( P . S^dagger ) with P,S the half-length link products.
//  Cold (U=1) values reproduce the paper (arXiv:2112.06340):
//    W6=8448 W8=245952 W10=7372800
//    P6(4)=1728   P8 w1=45792 w2=-384   P10 w1=645120 w2=-64512
// ===========================================================================

struct HPENode { int dir; double coeff; std::vector<int> child; };
struct HPEPair { int prefix; int suffix; double coeff; };

struct HPESector
{
  int half = 0;
  int maxreach = 0;                   // max geometric reach (= halo this sector needs)
  double factor = 0.;                 // -2 (Wilson) / +2 (Polyakov)
  std::vector<HPENode> ptree, stree;
  std::vector<HPEPair> pairs;
};

std::vector<int> hpe_cyclic_min( const std::vector<int>& t )
{
  const int L = t.size();
  std::vector<int> best( t );
  for( int s=1 ; s<L ; s++ ){
    std::vector<int> c( L );
    for( int n=0 ; n<L ; n++ ) c[n] = t[(s+n)%L];
    if( c < best ) best = c;
  }
  return best;
}

// geometric reach of a direction sequence measured from its start vertex
// (anchor = vertex 0): walk v_0..v_{L-1}, per-axis bbox [m_a,M_a] (m_a<=0<=M_a),
// reach = max_a max(M_a, -m_a) = the symmetric halo width this anchoring needs.
//
// SPATIAL axes only (a=0,1,2 = dir 1,2,3 = x,y,z). The time axis (a=3 = dir 4) is
// EXCLUDED: time is never MPI-split (div0=1, Nt small & periodic), so it needs no
// halo. Including it would (a) wrongly inflate the reach of time-winding Polyakov
// loops (up to ~m*Nt) and (b) make reach_min pick an anchor that minimises the
// irrelevant time excursion while leaving the spatial reach too large -> the trie
// then punches through the spatial halo. (If time is ever split, raise this to 4.)
int hpe_reach( const std::vector<int>& c )
{
  int m[4]={0,0,0,0}, M[4]={0,0,0,0}, p[4]={0,0,0,0};
  const int L = c.size();
  for( int k=0 ; k<L-1 ; k++ ){          // last step closes the loop (back to 0)
    const int a = std::abs(c[k]) - 1;
    p[a] += (c[k]>0) ? 1 : -1;
    if( p[a] < m[a] ) m[a] = p[a];
    if( p[a] > M[a] ) M[a] = p[a];
  }
  int r = 0;
  for( int a=0 ; a<3 ; a++ ){            // spatial only; a=3 (time) excluded
    const int e = std::max( M[a], -m[a] );
    if( e > r ) r = e;
  }
  return r;
}

// canonical anchor minimising geometric reach over all L cyclic rotations; ties
// broken by lexicographically smallest sequence -> consistent canonical form
// (trie dedup preserved). VALUE-PRESERVING: the loop trace is cyclic-invariant and
// the measurement sums over all sites, so re-rooting changes only the spatial
// footprint (required halo), never the result. Replaces hpe_cyclic_min so that the
// trie reaches only +-reach links from each site instead of +-L/2.
std::vector<int> hpe_reach_min( const std::vector<int>& t )
{
  const int L = t.size();
  std::vector<int> best( t );
  int bestR = hpe_reach( best );         // s = 0
  for( int s=1 ; s<L ; s++ ){
    std::vector<int> c( L );
    for( int n=0 ; n<L ; n++ ) c[n] = t[(s+n)%L];
    const int r = hpe_reach( c );
    if( r < bestR || ( r==bestR && c < best ) ){ bestR = r; best = c; }
  }
  return best;
}

int hpe_trie_insert( std::vector<HPENode>& tree , const std::vector<int>& dirs )
{
  int node = 0;
  for( int d : dirs ){
    int nx = -1;
    for( int c : tree[node].child )
      if( tree[c].dir == d ){ nx = c; break; }
    if( nx<0 ){
      nx = tree.size();
      tree.push_back( {d,0.,std::vector<int>()} );
      tree[node].child.push_back( nx );
    }
    node = nx;
  }
  return node;
}

HPESector hpe_build( const std::vector<std::vector<int>>& T ,
		     const std::vector<int>& D , bool poly )
{
  HPESector s;
  s.factor = poly ? 2. : -2.;
  s.ptree.push_back( {0,0.,std::vector<int>()} );
  s.stree.push_back( {0,0.,std::vector<int>()} );
  for( int i=0 ; i<(int)T.size() ; i++ ){
    if( D[i]==0 ) continue;
    const int L = T[i].size();
    s.half = L/2;
    const double coeff = D[i] / (double)cyclic_symmetry(T[i]);
    const auto orbit = poly ? MakeTrajListP(T[i]) : MakeTrajList(T[i]);
    for( const auto& tr : orbit ){
      const auto cm = hpe_reach_min( tr );
      const int rr = hpe_reach( cm );
      if( rr > s.maxreach ) s.maxreach = rr;
      std::vector<int> pre( cm.begin() , cm.begin()+s.half );
      std::vector<int> suf( s.half );
      for( int n=0 ; n<s.half ; n++ ) suf[n] = -cm[L-1-n];
      HPEPair pr;
      pr.prefix = hpe_trie_insert( s.ptree , pre );
      pr.suffix = hpe_trie_insert( s.stree , suf );
      pr.coeff  = coeff;
      s.pairs.push_back( pr );
    }
  }
  return s;
}

// length-12 以上は巨大なのでコンパイルせず実行時に .dat から読む
//   形式: 1行目 N, 続く各行 "D L d1 d2 ... dL"
HPESector hpe_build_file( const char* path , bool poly )
{
  std::ifstream f( path );
  if( !f ){ mdp << "ERROR: cannot open HPE table: " << path << endl; mpi.abort(); }
  int N; f >> N;
  std::vector<std::vector<int>> T(N); std::vector<int> D(N);
  for( int i=0 ; i<N ; i++ ){
    int d , L; f >> d >> L; D[i]=d; T[i].resize(L);
    for( int k=0 ; k<L ; k++ ) f >> T[i][k];
  }
  return hpe_build( T , D , poly );
}

void hpe_eval_half( const Gauge& V , const Site& x ,
		    const std::vector<HPENode>& tree ,
		    int node , double _Complex *Uptr )
{
  Matrix<3,3> tmp( Uptr + 9*node );
  for( int c : tree[node].child ){
    const int dir = tree[c].dir;
    const int mu = std::abs(dir) % 4;
    Matrix<3,3> tmp1( Uptr + 9*c );
    if( dir>0 )
      tmp1 = tmp * V(x,mu);
    else
      tmp1 = tmp * Hermite(V(x-mu,mu));
    Site xh = (dir>0) ? x+mu : x-mu;
    hpe_eval_half( V , xh , tree , c , Uptr );
  }
}

// complex loop trace  Tr( A . B^dagger ) = sum_k A_k conj(B_k)
double _Complex hpe_trace_AHB( const Matrix<3,3>& A , const Matrix<3,3>& B )
{
  double _Complex ans = 0.;
  for( int i=0 ; i<9 ; i++ )
    ans += A.address[i] * conj(B.address[i]);
  return ans;
}

// real part only:  Re Tr(A B^dagger) = sum_k [ Re A_k Re B_k + Im A_k Im B_k ]
// (half the work of the complex version; Wilson sectors are real)
double hpe_trace_AHB_re( const Matrix<3,3>& A , const Matrix<3,3>& B )
{
  double ans = 0.;
  for( int i=0 ; i<9 ; i++ )
    ans += __real__(A.address[i])*__real__(B.address[i])
         + __imag__(A.address[i])*__imag__(B.address[i]);
  return ans;
}

// Wilson sectors are real (loops come in conjugate pairs); Polyakov sectors
// (winding) are genuinely complex -> keep both real and imaginary parts.
double _Complex hpe_eval( const Gauge& V , const HPESector& s )
{
  double ar = 0. , ai = 0.;
  const auto& ptree = s.ptree;
  const auto& stree = s.stree;
  const auto& pairs = s.pairs;
#pragma omp parallel reduction( + : ar , ai )
  {
    std::vector<double _Complex> pptr( 9*ptree.size() );
    std::vector<double _Complex> sptr( 9*stree.size() );
    Site x(V.lattice());
    ForAllSitesOMP(x){
      Matrix<3,3> p0( pptr.data() ) , s0( sptr.data() );
      p0 = 1.;
      s0 = 1.;
      hpe_eval_half( V , x , ptree , 0 , pptr.data() );
      hpe_eval_half( V , x , stree , 0 , sptr.data() );
      for( const auto& pair : pairs ){
	const double _Complex t = hpe_trace_AHB(
	  Matrix<3,3>(pptr.data() + 9*pair.prefix) ,
	  Matrix<3,3>(sptr.data() + 9*pair.suffix) );
	ar += pair.coeff * __real__(t);
	ai += pair.coeff * __imag__(t);
      }
    }
  }
  mpi.add(ar);
  mpi.add(ai);
  double _Complex z;
  __real__ z = s.factor * ar / V.lattice().size();
  __imag__ z = s.factor * ai / V.lattice().size();
  return z;
}

// real-only evaluation for Wilson sectors (imaginary part vanishes): skips the
// imaginary accumulation entirely -> ~half the pair-trace cost.
double hpe_eval_real( const Gauge& V , const HPESector& s )
{
  double ar = 0.;
  const auto& ptree = s.ptree;
  const auto& stree = s.stree;
  const auto& pairs = s.pairs;
#pragma omp parallel reduction( + : ar )
  {
    std::vector<double _Complex> pptr( 9*ptree.size() );
    std::vector<double _Complex> sptr( 9*stree.size() );
    Site x(V.lattice());
    ForAllSitesOMP(x){
      Matrix<3,3> p0( pptr.data() ) , s0( sptr.data() );
      p0 = 1.;
      s0 = 1.;
      hpe_eval_half( V , x , ptree , 0 , pptr.data() );
      hpe_eval_half( V , x , stree , 0 , sptr.data() );
      for( const auto& pair : pairs )
	ar += pair.coeff * hpe_trace_AHB_re(
	  Matrix<3,3>(pptr.data() + 9*pair.prefix) ,
	  Matrix<3,3>(sptr.data() + 9*pair.suffix) );
    }
  }
  mpi.add(ar);
  return s.factor * ar / V.lattice().size();
}

// ---- cached sectors ------------------------------------------------------
const HPESector& sec_W6 () { static HPESector s = hpe_build( W6traj , W6D , false ); return s; }
const HPESector& sec_W8 () { static HPESector s = hpe_build( W8traj , W8D , false ); return s; }
const HPESector& sec_W10() { static HPESector s = hpe_build( W10traj, W10D, false ); return s; }
const HPESector& sec_P6 () { static HPESector s = hpe_build( P6Nt4traj    , P6Nt4D    , true ); return s; }
const HPESector& sec_P8w1(){ static HPESector s = hpe_build( P8Nt4traj_w1 , P8Nt4D_w1 , true ); return s; }
const HPESector& sec_P8w2(){ static HPESector s = hpe_build( P8Nt4traj_w2 , P8Nt4D_w2 , true ); return s; }
const HPESector& sec_P10w1(){static HPESector s = hpe_build( P10Nt4traj   , P10Nt4D   , true ); return s; }
const HPESector& sec_P10w2(){static HPESector s = hpe_build( P10Nt4traj_w2, P10Nt4D_w2, true ); return s; }
const HPESector& sec_W12 (){static HPESector s = hpe_build_file("trajectory_list/tables/w12_table.dat" , false); return s; }
const HPESector& sec_P12w1(){static HPESector s = hpe_build_file("trajectory_list/tables/p12_nt4_w1.dat", true ); return s; }
const HPESector& sec_P12w2(){static HPESector s = hpe_build_file("trajectory_list/tables/p12_nt4_w2.dat", true ); return s; }
const HPESector& sec_P12w3(){static HPESector s = hpe_build_file("trajectory_list/tables/p12_nt4_w3.dat", true ); return s; }

// ---- public per-length / per-winding values ------------------------------
// Wilson : real.   Polyakov : complex (winding -> nonzero imaginary part).
double HPE_W6 ( const Gauge& V ){ return hpe_eval_real( V , sec_W6()  ); }
double HPE_W8 ( const Gauge& V ){ return hpe_eval_real( V , sec_W8()  ); }
double HPE_W10( const Gauge& V ){ return hpe_eval_real( V , sec_W10() ); }

double _Complex HPE_P6   ( const Gauge& V ){ return hpe_eval( V , sec_P6()   ); }  // winding 1 only
double _Complex HPE_P8_w1( const Gauge& V ){ return hpe_eval( V , sec_P8w1() ); }
double _Complex HPE_P8_w2( const Gauge& V ){ return hpe_eval( V , sec_P8w2() ); }
double _Complex HPE_P8   ( const Gauge& V ){ return HPE_P8_w1(V) + HPE_P8_w2(V); }
double _Complex HPE_P10_w1( const Gauge& V ){ return hpe_eval( V , sec_P10w1() ); }
double _Complex HPE_P10_w2( const Gauge& V ){ return hpe_eval( V , sec_P10w2() ); }
double _Complex HPE_P10   ( const Gauge& V ){ return HPE_P10_w1(V) + HPE_P10_w2(V); }

double HPE_W12( const Gauge& V ){ return hpe_eval_real( V , sec_W12() ); }
double _Complex HPE_P12_w1( const Gauge& V ){ return hpe_eval( V , sec_P12w1() ); }
double _Complex HPE_P12_w2( const Gauge& V ){ return hpe_eval( V , sec_P12w2() ); }
double _Complex HPE_P12_w3( const Gauge& V ){ return hpe_eval( V , sec_P12w3() ); }
double _Complex HPE_P12   ( const Gauge& V ){ return HPE_P12_w1(V)+HPE_P12_w2(V)+HPE_P12_w3(V); }

// ===== Nt 適応 Polyakov レジストリ(tables/p<n>_nt<Nt>_w<m>.dat を input の Nt で選択) =====
struct HPEPolyEntry { int n, m; HPESector sec; };
static std::vector<HPEPolyEntry> g_poly;
void HPE_init_poly( int Nt , int Lmax=12 ){
  g_poly.clear();
  for( int n=6 ; n<=Lmax ; n+=2 )
    for( int m=1 ; m<= n/Nt ; m++ ){
      if( (n-m*Nt)%2 != 0 ) continue;
      char path[160]; sprintf( path , "trajectory_list/tables/p%d_nt%d_w%d.dat" , n , Nt , m );
      std::ifstream tf(path); if(!tf) continue;     // そのセクターが無ければ飛ばす
      g_poly.push_back( { n , m , hpe_build_file(path,true) } );
    }
}
int HPE_npoly(){ return (int)g_poly.size(); }
int HPE_poly_len ( int i ){ return g_poly[i].n; }
int HPE_poly_wind( int i ){ return g_poly[i].m; }
double _Complex HPE_poly_val( const Gauge& V , int i ){ return hpe_eval( V , g_poly[i].sec ); }

// ===== Wilson レジストリ(w<n>.dat, Nt 非依存)=====
struct HPEWilEntry { int n; HPESector sec; };
static std::vector<HPEWilEntry> g_wil;
void HPE_init_wilson( int Lmax=12 ){
  g_wil.clear();
  for( int n=6 ; n<=Lmax ; n+=2 ){
    char path[160]; sprintf( path , "trajectory_list/tables/w%d.dat" , n );
    std::ifstream tf(path); if(!tf) continue;
    g_wil.push_back( { n , hpe_build_file(path,false) } );
  }
}
int HPE_nwilson(){ return (int)g_wil.size(); }
int HPE_wilson_len( int i ){ return g_wil[i].n; }
double HPE_wilson_val( const Gauge& V , int i ){ return hpe_eval_real( V , g_wil[i].sec ); }

// 完全データ駆動の初期化: tables/ に置いた .dat の長さ(<=Lmax)まで Wilson+Polyakov を読む
void HPE_init( int Nt , int Lmax=12 ){ HPE_init_wilson(Lmax); HPE_init_poly(Nt,Lmax); }

// 実際に必要な halo 幅 = 読み込んだ全セクターの最大 reach (reach_min アンカー後)。
// 駆動側はこれを border に使い、CART_HALO 以下かを検証する (Lmax/2 ではなく実値)。
int HPE_maxreach(){
  int r = 0;
  for( const auto& e : g_wil )  if( e.sec.maxreach > r ) r = e.sec.maxreach;
  for( const auto& e : g_poly ) if( e.sec.maxreach > r ) r = e.sec.maxreach;
  return r;
}


